### ISSUE TITLE
App threw an error during load - Error: The specified module was not found.

### ISSUE THREAD

**Issue by Sv443** [open-unlight/node-discord-game#4]
I just installed this package and used the example code in the readme but when starting my app, I get this error:  
  
```
App threw an error during load
Error: The specified module was not found.
\\?\C:\Users\fes\Desktop\Code\TAG\node_modules\discord-game\build\Release\discord_game.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```  
  
Can you please help me fix this? It's not urgent but I'd like it to work in the near future.  
  
OS: Windows 10 x64  
Node: v12.16.1  
Electron: v8.0.2  
discord-game: v0.1.1

**Comment by elct9620** [comment]
Can you check for your `node_modules\discord-game\build\Release\discord_game.node` is exists or not?

The error message shows the compiled library cannot be found, maybe there has some problem when you install it.

**Comment by Sv443** [comment]
Yes it exists. I've also already tried reinstalling the package.  
  
![image](https://user-images.githubusercontent.com/38158426/80220333-f0da7180-8643-11ea-8242-0c3043c104d7.png)

**Comment by elct9620** [comment]
Which command you are using to start the app? Just use `electron .` to run it?

**Comment by Sv443** [comment]
I have been using both `electron .` and `npx electron .`, yes

**Comment by elct9620** [comment]
Can you try to downgrade to Electron 6.0 and try it again? Our project still using 6.0 and works well. If it has some compatibility problem with the Electron, it may need some time to schedule an upgrade plan to fix it.

**Comment by Sv443** [comment]
I'm afraid I can't downgrade. I've already built a lot of stuff and downgrading breaks everything and some features I need don't exist in Electron 6.

**Comment by elct9620** [comment]
@Sv443 

I create a Windows VM with Electron 8 and check for the reason.
You have to copy `discord_game_sdk.dll` to your project folder to let your Electron can find it correctly.

**Comment by Sv443** [comment]
Thank you! I completely missed that part and I'm sorry for wasting your time. I'm not able to test it at the moment but I will test it in the next couple of days and then either close this issue or tell you what went wrong.
